# Build settings
theme: minima
plugins:
  - jekyll-feed


domain: kruemelmann.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://kruemelmann.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /kruemelmann.github.io
